[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "1.1.2"
log = "0.4"
itertools = "=0.14.0"
spacetimedsl = "=0.5.0"

[logs]
level = "trace"
directives = [
    "spacetimedb=warn",
    "spacetimedb_standalone=info",
]

[modules]
entity_position = "src/entity_position"
