[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
spacetimedb-sdk = "1.11"
hex = "0.4"
rand = "0.9.1"
lazy_static = "1.5.0"
reqwest = { version = "*", features = ["blocking"] }
serde_json = "1.0.142"
